# Generated by Django 3.2.6 on 2023-01-03 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produccion', '0004_auto_20230103_0811'),
        ('Productos', '0007_auto_20230103_0811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_ingreso', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_ingresada', models.FloatField(verbose_name='Cantidad solicitada')),
                ('unidad_empaque', models.CharField(default='Kg', max_length=10, verbose_name='Unidad de empaque')),
                ('factura', models.CharField(blank=True, max_length=250, null=True, verbose_name='Factura')),
                ('remision', models.CharField(blank=True, max_length=250, null=True, verbose_name='Remisión')),
                ('lote', models.CharField(blank=True, max_length=250, null=True, verbose_name='lote')),
                ('observaciones_ingreso_materia_prima', models.TextField(blank=True, verbose_name='Observaciones Ingreso')),
                ('ingresado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresado', to=settings.AUTH_USER_MODEL)),
                ('ingreso_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_actualizado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingresos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion_PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_requisicion_pt_inventario', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_requisicion_pt', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('observaciones_PT', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion', verbose_name='Producto')),
                ('requisicion_pt_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicion_pt_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('requsicion_pt_creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requsicion_pt_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisicion Producto Terminado',
                'verbose_name_plural': 'Requisicion Producto Terminado',
                'db_table': 'Requisicion Producto Terminado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud_material', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho_material', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.CharField(default='Insumo', max_length=250, verbose_name='Proveedor')),
                ('cantidad_solicitada', models.FloatField(verbose_name='Cantidad solicitada')),
                ('observaciones_solicitud', models.TextField(blank=True, verbose_name='Observaciones Solicitud')),
                ('material_despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_despachado_por', to=settings.AUTH_USER_MODEL)),
                ('material_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.entrada', verbose_name='Material Solicitado')),
                ('material_solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_solicitado_por', to=settings.AUTH_USER_MODEL)),
                ('numero_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Requsición',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'Requisiciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Materia_Prima_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_material', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_material', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Inusmo', 'Insumo'), ('Pigmento', 'Pigmento')], max_length=30, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=250, verbose_name='Material o Insumo')),
                ('referencia', models.CharField(default='N/A', max_length=250, verbose_name='Referencia')),
                ('proveedor', models.CharField(max_length=250, verbose_name='Proveedor')),
                ('Unidad_Meidida', models.CharField(default='Kg', max_length=5, verbose_name='Unidad de Medida')),
                ('material_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('material_creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia Prima e Insumos',
                'verbose_name_plural': 'Materia Prima e Insumos',
                'db_table': 'Materia Prima e Insumos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_inventario', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_inventario', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_inicial', models.PositiveBigIntegerField(null=True, verbose_name='Cantidad inicial')),
                ('inventario_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('inventario_creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_creado_por', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos_colores', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto terminado',
                'verbose_name_plural': 'Producto terminado',
                'db_table': 'producto Terminado',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='ingreso_materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.materia_prima_insumo', verbose_name='Material Solicitado'),
        ),
    ]
