# Generated by Django 3.2.6 on 2022-07-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_ingreso', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_ingresada', models.FloatField(verbose_name='Cantidad solicitada')),
                ('unidad_empaque', models.CharField(default='Kg', max_length=10, verbose_name='Unidad de empaque')),
                ('factura', models.CharField(blank=True, max_length=250, null=True, verbose_name='Factura')),
                ('remision', models.CharField(blank=True, max_length=250, null=True, verbose_name='Remisión')),
                ('lote', models.CharField(blank=True, max_length=250, null=True, verbose_name='lote')),
                ('observaciones_ingreso_materia_prima', models.TextField(blank=True, verbose_name='Observaciones Ingreso')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingresos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_inventario', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_inventario', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Inicial')),
            ],
            options={
                'verbose_name': 'Producto terminado',
                'verbose_name_plural': 'Producto terminado',
                'db_table': 'producto Terminado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Materia_Prima_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_material', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_material', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Inusmo', 'Insumo')], max_length=30, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=250, verbose_name='Material o Insumo')),
                ('referencia', models.CharField(default='N/A', max_length=250, verbose_name='Referencia')),
                ('proveedor', models.CharField(max_length=250, verbose_name='Proveedor')),
                ('Unidad_Meidida', models.CharField(default='Kg', max_length=5, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Materia Prima e Insumos',
                'verbose_name_plural': 'Materia Prima e Insumos',
                'db_table': 'Materia Prima e Insumos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud_material', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho_material', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_solicitada', models.FloatField(verbose_name='Cantidad solicitada')),
                ('observaciones_solicitud', models.TextField(blank=True, verbose_name='Observaciones Solicitud')),
            ],
            options={
                'verbose_name': 'Requsición',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'Requisiciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion_PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_requisicion_pt_inventario', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_requisicion_pt', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('observaciones_PT', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.inventario', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Requisicion Producto Terminado',
                'verbose_name_plural': 'Requisicion Producto Terminado',
                'db_table': 'Requisicion Producto Terminado',
                'ordering': ['-id'],
            },
        ),
    ]
