# Generated by Django 3.2.6 on 2023-08-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0008_controlproduccion_material_molido'),
        ('Inventario', '0002_alter_materia_prima_insumo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='control_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control_produccion.controlproduccion', verbose_name='Control producción'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='categoria',
            field=models.CharField(default='Insumo', max_length=250, verbose_name='Categoria'),
        ),
    ]
