# Generated by Django 3.2.6 on 2022-08-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_prima_insumo',
            name='categoria',
            field=models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Inusmo', 'Insumo'), ('Pigmento', 'Pigmento')], max_length=30, verbose_name='Categoria'),
        ),
    ]
