# Generated by Django 3.2.6 on 2022-08-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_materia_prima_insumo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='categoria',
            field=models.CharField(default='Insumo', max_length=250, verbose_name='Proveedor'),
        ),
    ]
