# Generated by Django 3.2.6 on 2022-08-27 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20220730_1702'),
        ('Inventario', '0004_requisicion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos_colores', verbose_name='Producto'),
        ),
    ]
