# Generated by Django 3.2.6 on 2022-12-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20221016_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad_inicial',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Cantidad inicial'),
        ),
    ]
