# Generated by Django 3.2.6 on 2022-12-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_inventario_cantidad_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_inicial',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Cantidad inicial'),
        ),
    ]
