# Generated by Django 3.2.6 on 2023-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_inventario_cantidad_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_prima_insumo',
            name='categoria',
            field=models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Insumo', 'Insumo'), ('Pigmento', 'Pigmento')], max_length=30, verbose_name='Categoria'),
        ),
    ]
