# Generated by Django 3.2.6 on 2023-08-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0014_tiemposparadascontrolproduccion_observacion'),
        ('Inventario', '0009_alter_materia_prima_insumo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='control_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control_produccion.controlproduccion', verbose_name='Control producción'),
        ),
    ]
