# Generated by Django 3.2.6 on 2021-12-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PNC', '0001_initial'),
        ('Produccion', '0002_produccion_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productonoconforme',
            name='inspector_calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productonoconforme',
            name='inspector_calidad_actualiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_actualiza', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productonoconforme',
            name='numero_op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion', verbose_name='Número de Orden'),
        ),
    ]
