# Generated by Django 3.2.6 on 2022-10-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PNC', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo producto no conforme')),
            ],
            options={
                'verbose_name': 'Motivo producto no conforme',
                'verbose_name_plural': 'Motivos productos no conformes',
                'db_table': 'Motivos productos no conformes',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_1',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_10',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_2',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_3',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_4',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_5',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_6',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_7',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_8',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_9',
        ),
        migrations.AlterField(
            model_name='productonoconforme',
            name='estado_pnc',
            field=models.CharField(default='Pendiente', max_length=30, verbose_name='Estado PNC'),
        ),
        migrations.AddField(
            model_name='productonoconforme',
            name='tipo_pnc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PNC.motivopnc', verbose_name='Tipo PNC'),
        ),
    ]
