# Generated by Django 3.2.6 on 2023-01-03 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0006_auto_20230103_0811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PNC', '0003_remove_productonoconforme_numero_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo producto no conforme')),
            ],
            options={
                'verbose_name': 'Motivo producto no conforme',
                'verbose_name_plural': 'Motivos productos no conformes',
                'db_table': 'Motivos productos no conformes',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_1',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_10',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_2',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_3',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_4',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_5',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_6',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_7',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_8',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='tipo_pnc_9',
        ),
        migrations.AlterField(
            model_name='productonoconforme',
            name='estado_pnc',
            field=models.CharField(default='Pendiente', max_length=30, verbose_name='Estado PNC'),
        ),
        migrations.CreateModel(
            name='TrazabilidadProductoNoConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado_pnc', models.CharField(default='Pendiente', max_length=30, verbose_name='Estado PNC')),
                ('cantidad_pnc', models.PositiveIntegerField(verbose_name='Cantidad PNC')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_trazabilidad', to='Control_calidad.controlcalidad', verbose_name='Número de inspección')),
                ('inspector_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_trazabilidad', to=settings.AUTH_USER_MODEL)),
                ('inspector_calidad_actualiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_actualiza_trazabilidad', to=settings.AUTH_USER_MODEL)),
                ('tipo_pnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pnc_trazabilidad', to='PNC.motivopnc', verbose_name='Tipo PNC')),
            ],
            options={
                'verbose_name': 'Trazabilidad producto no conforme',
                'verbose_name_plural': 'Trazabilidad productos no conformes',
                'db_table': 'Trazabilidad productos no conformes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='productonoconforme',
            name='tipo_pnc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PNC.motivopnc', verbose_name='Tipo PNC'),
        ),
    ]
