# Generated by Django 3.2.6 on 2022-10-24 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0014_auto_20221021_1116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PNC', '0003_auto_20221023_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazabilidadProductoNoConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado_pnc', models.CharField(default='Pendiente', max_length=30, verbose_name='Estado PNC')),
                ('cantidad_pnc', models.PositiveIntegerField(verbose_name='Cantidad PNC')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_trazabilidad', to='Control_calidad.controlcalidad', verbose_name='Número de inspección')),
                ('inspector_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_trazabilidad', to=settings.AUTH_USER_MODEL)),
                ('inspector_calidad_actualiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_actualiza_trazabilidad', to=settings.AUTH_USER_MODEL)),
                ('tipo_pnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pnc_trazabilidad', to='PNC.motivopnc', verbose_name='Tipo PNC')),
            ],
            options={
                'verbose_name': 'Trazabilidad producto no conforme',
                'verbose_name_plural': 'Trazabilidad productos no conformes',
                'db_table': 'Trazabilidad productos no conformes',
                'ordering': ['-id'],
            },
        ),
    ]
