# Generated by Django 3.2.6 on 2022-07-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_produccion', '0001_initial'),
        ('Gestion_Humana', '0001_initial'),
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproduccion',
            name='numero_op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion', verbose_name='Número de orden'),
        ),
        migrations.AddField(
            model_name='controlproduccion',
            name='operario_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operario_produccion', to='Gestion_Humana.informacioncolaborador', verbose_name='Operario'),
        ),
    ]
