# Generated by Django 3.2.6 on 2022-07-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Humana', '0001_initial'),
        ('Control_produccion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproduccion',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlproduccion',
            name='supervisor_actualizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_actualizo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlproduccion',
            name='tecnico_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_produccion', to='Gestion_Humana.informacioncolaborador', verbose_name='Técnico'),
        ),
    ]
