# Generated by Django 3.2.6 on 2022-09-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0002_tecnicosoperarios'),
        ('Control_produccion', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproduccion',
            name='operario_produccion',
        ),
        migrations.RemoveField(
            model_name='controlproduccion',
            name='tecnico_produccion',
        ),
        migrations.CreateModel(
            name='ColaboradorControlProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Humana.tecnicosoperarios', verbose_name='Colaborador')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Control', to='Control_produccion.controlproduccion')),
            ],
            options={
                'verbose_name': 'Colaborador Control orden',
                'verbose_name_plural': 'Colaborador Controles de produccion',
                'db_table': 'Colaborador Controles de produccion',
                'ordering': ['-id'],
            },
        ),
    ]
