# Generated by Django 3.2.6 on 2022-09-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0004_auto_20220920_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproduccion',
            name='tiempo_paradas',
        ),
        migrations.CreateModel(
            name='TiemposParadasControlProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo Parada')),
                ('tiempo_paradas', models.DurationField(verbose_name='Tiempo de paradas')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Control_Parada', to='Control_produccion.controlproduccion')),
            ],
            options={
                'verbose_name': 'Tiempo de parada',
                'verbose_name_plural': 'Tiempos de paradas',
                'db_table': 'Tiempos de paradas',
                'ordering': ['-id'],
            },
        ),
    ]
