# Generated by Django 3.2.6 on 2023-02-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0005_alter_controlproduccion_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiemposparadascontrolproduccion',
            name='horas',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Horas'),
        ),
    ]
