# Generated by Django 3.2.6 on 2022-09-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0005_auto_20220921_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproduccion',
            name='tiempo_total_paradas',
            field=models.DurationField(null=True, verbose_name='Tiempo total de paradas'),
        ),
    ]
