# Generated by Django 3.2.6 on 2022-09-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0006_controlproduccion_tiempo_total_paradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosParadasControlProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo Parada')),
            ],
            options={
                'verbose_name': 'Motivo de parada',
                'verbose_name_plural': 'Motivos de paradas',
                'db_table': 'Motivos de paradas',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='tiemposparadascontrolproduccion',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Control_produccion.motivosparadascontrolproduccion', verbose_name='Motivo Parada'),
        ),
    ]
