# Generated by Django 3.2.6 on 2023-02-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0006_alter_tiemposparadascontrolproduccion_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemposparadascontrolproduccion',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='tiemposparadascontrolproduccion',
            name='horas',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Segundos'),
        ),
    ]
