# Generated by Django 3.2.6 on 2022-09-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0008_auto_20220923_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlproduccion',
            old_name='fecha_tuno',
            new_name='fecha_turno',
        ),
    ]
