# Generated by Django 3.2.6 on 2022-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0009_rename_fecha_tuno_controlproduccion_fecha_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproduccion',
            name='duracion_turno',
        ),
        migrations.RemoveField(
            model_name='controlproduccion',
            name='fecha_turno',
        ),
        migrations.AddField(
            model_name='controlproduccion',
            name='hora_final',
            field=models.DateTimeField(null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='controlproduccion',
            name='hora_inicio',
            field=models.DateTimeField(null=True, verbose_name='Hora inicio'),
        ),
    ]
