# Generated by Django 3.2.6 on 2022-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0010_auto_20220923_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiemposparadascontrolproduccion',
            name='tiempo_paradas',
        ),
        migrations.AddField(
            model_name='tiemposparadascontrolproduccion',
            name='minutos',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Minutos'),
        ),
        migrations.AddField(
            model_name='tiemposparadascontrolproduccion',
            name='segundos',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Segundos'),
        ),
    ]
