# Generated by Django 3.2.6 on 2022-09-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_produccion', '0011_auto_20220923_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposparadascontrolproduccion',
            old_name='segundos',
            new_name='horas',
        ),
    ]
