# Generated by Django 3.2.6 on 2022-07-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_calidad', '0001_initial'),
        ('Produccion', '0002_produccion_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Humana', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebascalidad',
            name='inspector_actualizo_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_actualizo_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='inspector_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='pruebas_y_o_ensayos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.pruebasensayo', verbose_name='Pruebas y/o ensayos'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='id_inspeccion_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_calidad.controlcalidad', verbose_name='Número de inspección'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='inspeccion_dimensional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.caracteristicasdimensionale', verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='inspector_actualizo_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_actualizo_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='inspector_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspeccionatributos',
            name='id_inspeccion_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_calidad.controlcalidad', verbose_name='Número de inspección'),
        ),
        migrations.AddField(
            model_name='inspeccionatributos',
            name='inspeccion_atributos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.controlatributo', verbose_name='Atributos'),
        ),
        migrations.AddField(
            model_name='inspeccionatributos',
            name='inspector_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspeccionatributos',
            name='inspector_actualizo_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_actualizo_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='inspector_actualizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_actualizo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='numero_op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion', verbose_name='Número de orden'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='operario_calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operario_calidad', to='Gestion_Humana.informacioncolaborador', verbose_name='Operario'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='tecnico_calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_calidad', to='Gestion_Humana.informacioncolaborador', verbose_name='Técnico'),
        ),
    ]
