# Generated by Django 3.2.6 on 2021-12-20 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_pruebasensayo_tolerancia_p'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control_calidad', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pruebas',
            new_name='PruebasCalidad',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='producto',
        ),
    ]
