# Generated by Django 3.2.6 on 2022-08-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cavidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Valor')),
                ('id_inspeccion_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_calidad.controlcalidad', verbose_name='Número de inspección')),
            ],
            options={
                'verbose_name': 'Cavidad',
                'verbose_name_plural': 'Cavidades',
                'db_table': 'Cavidad',
                'ordering': ['-id'],
            },
        ),
    ]
