# Generated by Django 3.2.6 on 2021-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0003_auto_20211220_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionatributos',
            name='resultado_ia',
            field=models.CharField(max_length=30, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='resultado_id',
            field=models.CharField(max_length=30, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='resultado_p',
            field=models.CharField(max_length=30, verbose_name='Resultado'),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
