# Generated by Django 3.2.6 on 2022-05-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0004_auto_20211220_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente Despacho'),
        ),
    ]
