# Generated by Django 3.2.6 on 2023-01-03 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Gestion_Humana', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control_calidad', '0005_controlcalidad_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='empaque_y_embalaje',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='fecha_despacho',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='pruebascalidad',
            name='metodo_p',
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_1',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_1'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_10',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_10'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_11',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_11'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_12',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_12'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_13',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_13'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_14',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_14'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_15',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_15'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_16',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_16'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_17',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_17'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_18',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_18'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_19',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_19'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_2',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_2'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_20',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_20'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_21',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_21'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_22',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_22'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_23',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_23'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_24',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_24'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_25',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_25'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_26',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_26'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_27',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_27'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_28',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_28'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_29',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_29'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_3',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_3'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_30',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_30'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_31',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_31'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_32',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_32'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_4',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_4'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_5',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_5'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_6',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_6'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_7',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_7'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_8',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_8'),
        ),
        migrations.AddField(
            model_name='inspecciondimensional',
            name='cavidad_9',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_9'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_1',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_1'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_10',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_10'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_11',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_11'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_12',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_12'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_13',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_13'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_14',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_14'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_15',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_15'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_16',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_16'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_17',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_17'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_18',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_18'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_19',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_19'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_2',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_2'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_20',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_20'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_21',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_21'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_22',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_22'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_23',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_23'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_24',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_24'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_25',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_25'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_26',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_26'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_27',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_27'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_28',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_28'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_29',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_29'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_3',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_3'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_30',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_30'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_31',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_31'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_32',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_32'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_4',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_4'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_5',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_5'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_6',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_6'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_7',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_7'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_8',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_8'),
        ),
        migrations.AddField(
            model_name='pruebascalidad',
            name='cavidad_9',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_9'),
        ),
        migrations.CreateModel(
            name='NivelDeInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nivel', models.CharField(choices=[('Niveles especiales de inspección', 'Niveles especiales de inspección'), ('Niveles normales de inspección', 'Niveles normales de inspección')], default='1', max_length=100, verbose_name='Tipo Nivel')),
                ('codigo_nivel', models.CharField(choices=[('S-1', 'S-1'), ('S-2', 'S-1'), ('S-3', 'S-1'), ('S-4', 'S-1'), ('1', '1'), ('2', '2'), ('3', '3')], default='S-1', max_length=10, verbose_name='Código Nivel')),
                ('cantidades_inspeccionar', models.PositiveIntegerField(default=0, verbose_name='Cantidades a inspeccionar')),
                ('letra', models.CharField(default='', max_length=5)),
                ('inspeccion_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_calidad', to='Control_calidad.controlcalidad', verbose_name='Inspección Calidad')),
            ],
            options={
                'verbose_name': 'Nivel de inspección',
                'verbose_name_plural': 'Niveles de inspección',
                'db_table': 'Niveles de inspección',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('arte_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arte cliente')),
                ('unidades_muestra', models.PositiveBigIntegerField(verbose_name='Cantidad de unidades de muestra')),
                ('unidades_lote', models.PositiveBigIntegerField(verbose_name='Cantidad de unidades del lote')),
                ('lote', models.CharField(default='', max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('fecha_lote', models.DateField(verbose_name='Fecha de fabricación')),
                ('arte_ingreso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arte ingreso')),
                ('unidades_empaque', models.PositiveBigIntegerField(verbose_name='Cantidad de unidades de empaque revisadas')),
                ('certificado', models.BooleanField(default=False, verbose_name='Certificado de calidad')),
                ('especificaciones', models.BooleanField(default=False, verbose_name='Cumple especificaciones')),
                ('lote_ingreso', models.BooleanField(verbose_name='Coincide con lote de ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('revisado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revisado por')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('tolerado', models.BooleanField(default=False, verbose_name='Tolerado')),
                ('estado', models.CharField(choices=[('Conforme', 'Conforme'), ('Retenido', 'Retenido'), ('En devolución', 'En devolución'), ('Devuelto', 'Devuelto'), ('Conciliado', 'Conciliado'), ('En espera', 'En espera')], default='En espera', max_length=40, verbose_name='Estado del material')),
                ('inspector_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_mp', to=settings.AUTH_USER_MODEL)),
                ('inspector_calidad_actualizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_calidad_actualizo_mp', to=settings.AUTH_USER_MODEL)),
                ('materia_prima_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima_insumo', to='Inventario.entrada')),
            ],
            options={
                'verbose_name': 'Inspección a materia prima e insumos',
                'verbose_name_plural': 'Inspecciones a materia prima e insumos',
                'db_table': 'Inspección materia prima e insumos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dimensional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Especificación')),
                ('muestra_1', models.FloatField(blank=True, null=True, verbose_name='muestra_1')),
                ('muestra_2', models.FloatField(blank=True, null=True, verbose_name='muestra_2')),
                ('muestra_3', models.FloatField(blank=True, null=True, verbose_name='muestra_3')),
                ('muestra_4', models.FloatField(blank=True, null=True, verbose_name='muestra_4')),
                ('muestra_5', models.FloatField(blank=True, null=True, verbose_name='muestra_5')),
                ('muestra_6', models.FloatField(blank=True, null=True, verbose_name='muestra_6')),
                ('muestra_7', models.FloatField(blank=True, null=True, verbose_name='muestra_7')),
                ('muestra_8', models.FloatField(blank=True, null=True, verbose_name='muestra_8')),
                ('muestra_9', models.FloatField(blank=True, null=True, verbose_name='muestra_9')),
                ('muestra_10', models.FloatField(blank=True, null=True, verbose_name='muestra_10')),
                ('muestra_11', models.FloatField(blank=True, null=True, verbose_name='muestra_11')),
                ('muestra_12', models.FloatField(blank=True, null=True, verbose_name='muestra_12')),
                ('muestra_13', models.FloatField(blank=True, null=True, verbose_name='muestra_13')),
                ('cumple', models.CharField(default='Cumple', max_length=40, verbose_name='Cumple')),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analisis_dimensional', to='Control_calidad.materiaprimainsumos')),
            ],
            options={
                'verbose_name': 'Inspeccion a dimensiones mp',
                'verbose_name_plural': 'Inspecciones a dimensiones mp',
                'db_table': 'Inspecciones a dimensiones mp',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ColaboradorInspeccionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Humana.tecnicosoperarios', verbose_name='Colaborador')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Control', to='Control_calidad.controlcalidad')),
            ],
            options={
                'verbose_name': 'Colaborador Inspección Calidad',
                'verbose_name_plural': 'Colaboradores Inpección Calidad',
                'db_table': 'Colaboradores Inpección Calidad',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CertificadosCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_certificado', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_despacho', models.DateField(null=True, verbose_name='Fecha despacho')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0, verbose_name='Cantidad solicitada')),
                ('empaque_y_embalaje', models.TextField(blank=True, verbose_name='Empaque y embalaje')),
                ('cliente_despacho', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente Despacho')),
                ('certificado_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generado_por', to=settings.AUTH_USER_MODEL)),
                ('inspeccion_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_calidad', to='Control_calidad.controlcalidad', verbose_name='Número de inspección')),
            ],
            options={
                'verbose_name': 'Certificado de calidad',
                'verbose_name_plural': 'Certificados de calidad',
                'db_table': 'Certificados de calidad',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=40, verbose_name='Especificación')),
                ('cumple', models.CharField(max_length=40, verbose_name='Cumple')),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analisis', to='Control_calidad.materiaprimainsumos')),
            ],
            options={
                'verbose_name': 'Analisis de atributos y funcional',
                'verbose_name_plural': 'Analisis de atributos y funcional',
                'db_table': 'Analisis de atributos y funcional',
                'ordering': ['-id'],
            },
        ),
    ]
