# Generated by Django 3.2.6 on 2022-05-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20220402_2316'),
        ('Control_calidad', '0005_controlcalidad_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionatributos',
            name='id_inspeccion_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_calidad.controlcalidad', verbose_name='Número de inspección'),
        ),
        migrations.AlterField(
            model_name='inspeccionatributos',
            name='inspeccion_atributos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.controlatributo', verbose_name='Atributos'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='id_inspeccion_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_calidad.controlcalidad', verbose_name='Número de inspección'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='inspeccion_dimensional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.caracteristicasdimensionale', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='id_inspeccion_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_calidad.controlcalidad', verbose_name='Número de inspección'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='pruebas_y_o_ensayos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.pruebasensayo', verbose_name='Pruebas y/o ensayos'),
        ),
    ]
