# Generated by Django 3.2.6 on 2023-01-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0006_auto_20230103_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprimainsumos',
            name='certificado_proveedor',
            field=models.FileField(blank=True, null=True, upload_to='Control_calidad/Certificado_proveedores', verbose_name='Certificado proveedor'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='turno',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10, verbose_name='Turno'),
        ),
    ]
