# Generated by Django 3.2.6 on 2022-10-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0007_auto_20221003_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_1',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_1'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_10',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_10'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_11',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_11'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_12',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_12'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_13',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_13'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_14',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_14'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_15',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_15'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_16',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_16'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_17',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_17'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_18',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_18'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_19',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_19'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_2',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_2'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_20',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_20'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_21',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_21'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_22',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_22'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_23',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_23'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_24',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_24'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_25',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_25'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_26',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_26'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_27',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_27'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_28',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_28'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_29',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_29'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_3',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_3'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_30',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_30'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_31',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_31'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_32',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_32'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_4',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_4'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_5',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_5'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_6',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_6'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_7',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_7'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_8',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_8'),
        ),
        migrations.AlterField(
            model_name='inspecciondimensional',
            name='cavidad_9',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_9'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_1',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_1'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_10',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_10'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_11',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_11'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_12',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_12'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_13',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_13'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_14',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_14'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_15',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_15'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_16',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_16'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_17',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_17'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_18',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_18'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_19',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_19'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_2',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_2'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_20',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_20'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_21',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_21'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_22',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_22'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_23',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_23'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_24',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_24'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_25',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_25'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_26',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_26'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_27',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_27'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_28',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_28'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_29',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_29'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_3',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_3'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_30',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_30'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_31',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_31'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_32',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_32'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_4',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_4'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_5',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_5'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_6',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_6'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_7',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_7'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_8',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_8'),
        ),
        migrations.AlterField(
            model_name='pruebascalidad',
            name='cavidad_9',
            field=models.FloatField(blank=True, null=True, verbose_name='cavidad_9'),
        ),
    ]
