# Generated by Django 3.2.6 on 2022-10-05 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control_calidad', '0008_auto_20221003_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='empaque_y_embalaje',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='fecha_despacho',
        ),
        migrations.CreateModel(
            name='CertificadosCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_certificado', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_despacho', models.DateField(null=True, verbose_name='Fecha despacho')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0, verbose_name='Cantidad solicitada')),
                ('empaque_y_embalaje', models.TextField(blank=True, verbose_name='Empaque y embalaje')),
                ('cliente_despacho', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente Despacho')),
                ('certificado', models.FileField(upload_to='Control_calidad/Certificados', verbose_name='Certificado')),
                ('certificado_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generado_por', to=settings.AUTH_USER_MODEL)),
                ('inspeccion_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_calidad', to='Control_calidad.controlcalidad', verbose_name='Número de inspección')),
            ],
            options={
                'verbose_name': 'Certificado de calidad',
                'verbose_name_plural': 'Certificados de calidad',
                'db_table': 'Certificados de calidad',
                'ordering': ['-id'],
            },
        ),
    ]
