# Generated by Django 3.2.6 on 2022-10-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0011_certificadoscalidad_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoscalidad',
            name='certificado',
        ),
    ]
