# Generated by Django 3.2.6 on 2022-10-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0012_remove_certificadoscalidad_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDeInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nivel', models.CharField(choices=[('Niveles especiales de inspección', 'Niveles especiales de inspección'), ('Niveles normales de inspección', 'Niveles normales de inspección')], default='1', max_length=100, verbose_name='Tipo Nivel')),
                ('codigo_nivel', models.CharField(choices=[('S-1', 'S-1'), ('S-2', 'S-1'), ('S-3', 'S-1'), ('S-4', 'S-1'), ('1', '1'), ('2', '2'), ('3', '3')], default='S-1', max_length=10, verbose_name='Código Nivel')),
                ('inspeccion_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_calidad', to='Control_calidad.controlcalidad', verbose_name='Inspección Calidad')),
            ],
            options={
                'verbose_name': 'Nivel de inspección',
                'verbose_name_plural': 'Niveles de inspección',
                'db_table': 'Niveles de inspección',
                'ordering': ['-id'],
            },
        ),
    ]
