# Generated by Django 3.2.6 on 2022-12-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0015_analisis_dimensional_materiaprimainsumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensional',
            name='cumple',
            field=models.CharField(default='Cumple', max_length=40, verbose_name='Cumple'),
        ),
    ]
