# Generated by Django 3.2.6 on 2022-12-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0017_dimensional_especificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprimainsumos',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='materiaprimainsumos',
            name='certificado',
            field=models.BooleanField(default=False, verbose_name='Certificado de calidad'),
        ),
        migrations.AlterField(
            model_name='materiaprimainsumos',
            name='especificaciones',
            field=models.BooleanField(default=False, verbose_name='Cumple especificaciones'),
        ),
        migrations.AlterField(
            model_name='materiaprimainsumos',
            name='tolerado',
            field=models.BooleanField(default=False, verbose_name='Tolerado'),
        ),
    ]
