# Generated by Django 3.2.6 on 2022-12-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0018_auto_20221228_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprimainsumos',
            name='lote',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiaprimainsumos',
            name='estado',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('Retenido', 'Retenido'), ('En devolución', 'En devolución'), ('Devuelto', 'Devuelto'), ('Conciliado', 'Conciliado'), ('En espera', 'En espera')], default='En espera', max_length=40, verbose_name='Estado del material'),
        ),
    ]
