# Generated by Django 3.2.6 on 2023-01-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0019_auto_20221228_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='turno',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10, verbose_name='Turno'),
        ),
    ]
