# Generated by Django 3.2.6 on 2023-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0020_alter_controlcalidad_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprimainsumos',
            name='certificado_proveedor',
            field=models.FileField(blank=True, null=True, upload_to='Control_calidad/Certificado_proveedores', verbose_name='Certificado proveedor'),
        ),
    ]
