# Generated by Django 3.2.6 on 2023-02-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_calidad', '0021_materiaprimainsumos_certificado_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoscalidad',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código cliente'),
        ),
        migrations.AddField(
            model_name='certificadoscalidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
