# Generated by Django 3.2.6 on 2021-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('Procedimiento', 'Procedimiento'), ('Instructivo', 'Instructivo'), ('Formato', 'Formato'), ('Matriz', 'Matriz'), ('Plan', 'Plan'), ('Manual', 'Manual'), ('Politica', 'Politica'), ('Programa', 'Programa'), ('Documento externo', 'Documento externo'), ('Norma', 'Norma')], max_length=50, verbose_name='Tipo de documento')),
                ('proceso', models.CharField(max_length=100, verbose_name='Proceso')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('versión', models.PositiveIntegerField(verbose_name='Versión')),
                ('fecha', models.DateField(verbose_name='Fecha de vigencia')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('medio_almacenamiento', models.CharField(choices=[('Físico', 'Físico'), ('Digital', 'Digital')], max_length=20, verbose_name='Medio de almacenamiento')),
                ('estado_documento', models.CharField(choices=[('Vigente', 'Vigente'), ('Obsoleto', 'Obsoleto'), ('En elaboración', 'En elaboración'), ('En aprobación', 'En aprobación'), ('En revisión', 'En revisión')], max_length=40, verbose_name='Estado del documento')),
                ('se_trasnforma_registro', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=7, verbose_name='Se transforma en registro?')),
                ('dependencia_lider', models.CharField(max_length=80, verbose_name='Dependencia lider')),
                ('control_cambios', models.TextField(blank=True, verbose_name='Control de cambios')),
                ('documento', models.FileField(upload_to='Documentación/Documentos', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documentos',
                'ordering': ['-id'],
            },
        ),
    ]
