# Generated by Django 3.2.6 on 2022-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentación', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='tipo_documento',
            field=models.CharField(choices=[('Procedimiento', 'Procedimiento'), ('Instructivo', 'Instructivo'), ('Formato', 'Formato'), ('Matriz', 'Matriz'), ('Plan', 'Plan'), ('Manual', 'Manual'), ('Politica', 'Politica'), ('Programa', 'Programa'), ('Documento externo', 'Documento externo'), ('Norma', 'Norma'), ('Ficha Técnica', 'Ficha Técnica'), ('Certificado', 'Certificado')], max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación'),
        ),
    ]
