# Generated by Django 3.2.6 on 2022-08-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20220730_1702'),
        ('Produccion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos_colores', verbose_name='Nombre del Producto'),
        ),
    ]
