# Generated by Django 3.2.6 on 2023-01-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0004_auto_20230103_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='lote',
        ),
    ]
