# Generated by Django 3.2.6 on 2023-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0006_alter_produccion_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='fecha_inicio_produccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio de producción'),
        ),
    ]
