# Generated by Django 3.2.6 on 2022-08-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0008_auto_20220808_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='aprobacion_material',
        ),
        migrations.AddField(
            model_name='produccion',
            name='aprobacion_materia_prima',
            field=models.BooleanField(default=False, verbose_name='Aprobación materia prima'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='aprobacion_pigmento',
            field=models.BooleanField(default=False, verbose_name='Aprobación pigmento'),
        ),
    ]
