# Generated by Django 3.2.6 on 2022-08-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0009_auto_20220808_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='usuario_actualizo',
        ),
    ]
