# Generated by Django 3.2.6 on 2024-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0009_alter_produccion_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='maquina',
            field=models.CharField(choices=[('', ''), ('Sin asignar', 'Sin asignar'), ('Inyectora 1', 'Inyectora 1'), ('Inyectora 2', 'Inyectora 2'), ('Inyectora 3', 'Inyectora 3'), ('Inyectora 4', 'Inyectora 4'), ('Inyectora 5', 'Inyectora 5'), ('Inyectora 6', 'Inyectora 6'), ('Inyectora 7', 'Inyectora 7'), ('Inyectora 8', 'Inyectora 8'), ('Inyectora 9', 'Inyectora 9'), ('Sopladora 1', 'Sopladora 1'), ('Sopladora 2', 'Sopladora 2'), ('Sopladora 3', 'Sopladora 3'), ('Maquila', 'Maquila'), ('Maquila Plastyar', 'Maquila Plastyar'), ('Maquila Richard', 'Maquila Richard'), ('Maquila Gandyplast', 'Maquila Gandyplast'), ('Ensamble', 'Ensamble')], default='', max_length=40, verbose_name='Máquina'),
        ),
    ]
