# Generated by Django 3.2.6 on 2022-08-17 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produccion', '0011_produccion_usuario_actualizo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='usuario_actualizo',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
