# Generated by Django 3.2.6 on 2023-01-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0014_auto_20230102_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollo',
            name='fecha_analisis_muestras',
            field=models.DateField(null=True, verbose_name='Fecha análisis de muestras'),
        ),
    ]
