# Generated by Django 3.2.6 on 2023-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0018_alter_produccion_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='maquina',
            field=models.CharField(choices=[('', ''), ('Sin asignar', 'Sin asignar'), ('Inyectora 1', 'Inyectora 1'), ('Inyectora 2', 'Inyectora 2'), ('Inyectora 3', 'Inyectora 3'), ('Inyectora 4', 'Inyectora 4'), ('Inyectora 5', 'Inyectora 5'), ('Inyectora 6', 'Inyectora 6'), ('Sopladora 1', 'Sopladora 1'), ('Sopladora 2', 'Sopladora 2'), ('Sopladora 3', 'Sopladora 3'), ('Maquila', 'Maquila'), ('Ensamble', 'Ensamble')], default='', max_length=40, verbose_name='Máquina'),
        ),
    ]
