# Generated by Django 3.2.6 on 2023-01-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('tipo_documento', models.CharField(choices=[('Cedula', 'Cedula'), ('Cedula de extrangeria', 'Cedula de extrangeria')], max_length=40, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Número de documento')),
                ('fotocopia_documento', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Documento', verbose_name='Fotocopia documento')),
                ('hijos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hijos')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Curriculum', verbose_name='Hoja de vida')),
                ('certificado_laboral', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Certificados_laborales', verbose_name='Certificaciones laborales')),
                ('certificado_academico', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Certificados_academicos', verbose_name='Certificaciones académicas')),
                ('referencias', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Referencias', verbose_name='Referencias laborales')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Gestion_Humana/fFotos', verbose_name='Foto')),
                ('telefono_contacto', models.PositiveIntegerField(verbose_name='Teléfono de contacto')),
                ('nombre_emergencia', models.CharField(max_length=150, verbose_name='Nombres y apellidos contacto de emergencia')),
                ('parentezco', models.CharField(max_length=60, verbose_name='Parentezco')),
                ('telefono_emergencia', models.PositiveIntegerField(verbose_name='Teléfono de contacto de emergencia')),
                ('jefe_inmediato', models.CharField(max_length=60, verbose_name='Jefe inmediato')),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo'), ('Obra o labor', 'Obra o labor'), ('Aprendizaje', 'Aprendizaje'), ('Temporal', 'Temporal'), ('Ocasional', 'Ocasional'), ('Accidental', 'Accidental')], max_length=50, verbose_name='Tipo de contrato')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Contratos', verbose_name='Contrato')),
                ('afiliaciones', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Afiliaciones', verbose_name='Afiliaciones')),
                ('examen_ingreso', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Examenes', verbose_name='Examenes de ingreso')),
                ('carta_terminacion', models.FileField(blank=True, null=True, upload_to='Gestion_Humana/Terminacion', verbose_name='Carta terminación de contrato')),
                ('cargo', models.CharField(max_length=60, verbose_name='Cargo')),
                ('proceso', models.CharField(max_length=60, verbose_name='Proceso al que pertenece')),
                ('fecha_vinculacion', models.DateField(verbose_name='Fecha de vinculación')),
                ('fecha_desvinculacion', models.DateField(blank=True, null=True, verbose_name='Fecha de desvinculación')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'Colaboradores',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TecnicosOperarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(choices=[('Técnico', 'Técnico'), ('Operario', 'Operario')], max_length=50, verbose_name='Cargo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Técnicos y Operarios',
                'verbose_name_plural': 'Técnicos y Operarios',
                'db_table': 'Técnicos y Operarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesosDisciplinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_falta', models.TextField(verbose_name='Informe de la falta')),
                ('carta_citacion', models.FileField(upload_to='Gestion_Humana/Cartas_citacion', verbose_name='Carta de citación a descargos')),
                ('acta', models.FileField(upload_to='Gestion_Humana/Actas_descargos', verbose_name='Acta de descargos')),
                ('decision', models.CharField(choices=[('Llamada de atención', 'Llamada de atención'), ('Sanción', 'Sanción'), ('Despido', 'Despido')], max_length=30, verbose_name='Decisión')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Humana.informacioncolaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Proceso disciplinario',
                'verbose_name_plural': 'Procesos disciplinarios',
                'db_table': 'Procesos disciplinarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OtroSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=40, verbose_name='Tema del otro si')),
                ('otro_si', models.FileField(upload_to='Gestion_Humana/Otro_Si', verbose_name='Otro si')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Humana.informacioncolaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Otro Si',
                'verbose_name_plural': 'Otro Si',
                'db_table': 'Otro Si',
                'ordering': ['-id'],
            },
        ),
    ]
