# Generated by Django 3.2.6 on 2023-02-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0002_auto_20230129_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='numero_documento',
            field=models.BigIntegerField(verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='telefono_contacto',
            field=models.BigIntegerField(verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='telefono_emergencia',
            field=models.BigIntegerField(verbose_name='Teléfono de contacto de emergencia'),
        ),
    ]
