# Generated by Django 3.2.6 on 2022-10-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0003_auto_20221026_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='cargo',
            field=models.CharField(max_length=60, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='fecha_vinculacion',
            field=models.DateField(verbose_name='Fecha de vinculación'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='jefe_inmediato',
            field=models.CharField(max_length=60, verbose_name='Jefe inmediato'),
        ),
        migrations.AlterField(
            model_name='informacioncolaborador',
            name='tipo_contrato',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo'), ('Obra o labor', 'Obra o labor'), ('Aprendizaje', 'Aprendizaje'), ('Temporal', 'Temporal'), ('Ocasional', 'Ocasional'), ('Accidental', 'Accidental')], max_length=50, verbose_name='Tipo de contrato'),
        ),
    ]
