# Generated by Django 3.2.6 on 2023-07-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0005_auto_20230222_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Turno 1', 'Turno 1'), ('Turno 2', 'Turno 2'), ('Turno 3', 'Turno 3'), ('Turno 4', 'Turno 4'), ('Turno 5', 'Turno 5'), ('Turno 6', 'Turno 6'), ('Vacaciones', 'Vacaciones'), ('Incapacidad', 'Incapacidad'), ('Otros', 'Otros'), ('Licencia no remunerada', 'Licencia no remunerada')], max_length=50, verbose_name='Turno')),
                ('fecha_programacion', models.DateField(verbose_name='Fecha programación')),
                ('maquina', models.CharField(choices=[('', ''), ('Sin asignar', 'Sin asignar'), ('Inyectora 1', 'Inyectora 1'), ('Inyectora 2', 'Inyectora 2'), ('Inyectora 3', 'Inyectora 3'), ('Inyectora 4', 'Inyectora 4'), ('Inyectora 5', 'Inyectora 5'), ('Inyectora 6', 'Inyectora 6'), ('Inyectora 7', 'Inyectora 7'), ('Sopladora 1', 'Sopladora 1'), ('Sopladora 2', 'Sopladora 2'), ('Sopladora 3', 'Sopladora 3'), ('Maquila', 'Maquila'), ('Ensamble', 'Ensamble')], max_length=100, verbose_name='Máquina')),
                ('cumplimiento', models.BooleanField(default=True, verbose_name='Cumplimiento programación')),
                ('motivo_incumplimiento', models.CharField(blank=True, choices=[('Calamidad domestica', 'Calamidad domestica'), ('Incapacidad EPS', 'Incapacidad EPS'), ('Permiso remunerado', 'Permiso remunerado'), ('Permiso no remunerado', 'Permiso no remunerado'), ('Cambio de turno', 'Cambio de turno'), ('Día de la familia', 'Día de la familia'), ('Renuncia', 'Renuncia'), ('Daño máquina', 'Daño máquina'), ('Falta de material', 'Falta de material'), ('Incapacidad ARL', 'Incapacidad ARL'), ('No justificado', 'No justificado'), ('Vacaciones', 'Vacaciones')], max_length=100, null=True, verbose_name='Motivo incumplimiento')),
                ('turno_reprogramacion', models.CharField(blank=True, choices=[('Turno 1', 'Turno 1'), ('Turno 2', 'Turno 2'), ('Turno 3', 'Turno 3'), ('Turno 4', 'Turno 4'), ('Turno 5', 'Turno 5'), ('Turno 6', 'Turno 6'), ('Vacaciones', 'Vacaciones'), ('Incapacidad', 'Incapacidad'), ('Otros', 'Otros'), ('Licencia no remunerada', 'Licencia no remunerada')], max_length=50, null=True, verbose_name='Turno reprogramación')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Humana.tecnicosoperarios', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programación',
                'db_table': 'Programación',
                'ordering': ['-id'],
            },
        ),
    ]
