# Generated by Django 3.2.6 on 2023-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0006_informacioncolaborador_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenesmedicos',
            name='motivo',
            field=models.CharField(choices=[('Periodico', 'Periodico'), ('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], max_length=50, verbose_name='Motivo'),
        ),
    ]
