# Generated by Django 3.2.6 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0009_programacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='cumplimiento',
            field=models.BooleanField(default=True, verbose_name='Cumplimiento programación'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='maquina',
            field=models.CharField(choices=[('', ''), ('Sin asignar', 'Sin asignar'), ('Inyectora 1', 'Inyectora 1'), ('Inyectora 2', 'Inyectora 2'), ('Inyectora 3', 'Inyectora 3'), ('Inyectora 4', 'Inyectora 4'), ('Inyectora 5', 'Inyectora 5'), ('Inyectora 6', 'Inyectora 6'), ('Inyectora 7', 'Inyectora 7'), ('Sopladora 1', 'Sopladora 1'), ('Sopladora 2', 'Sopladora 2'), ('Sopladora 3', 'Sopladora 3'), ('Maquila', 'Maquila'), ('Ensamble', 'Ensamble')], max_length=100, verbose_name='Máquina'),
        ),
    ]
