# Generated by Django 3.2.6 on 2023-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Humana', '0010_auto_20230616_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='turno_reprogramacion',
            field=models.CharField(blank=True, choices=[('Turno 1', 'Turno 1'), ('Turno 2', 'Turno 2'), ('Turno 3', 'Turno 3'), ('Turno 4', 'Turno 4'), ('Turno 5', 'Turno 5'), ('Turno 6', 'Turno 6'), ('Vacaciones', 'Vacaciones'), ('Incapacidad', 'Incapacidad'), ('Otros', 'Otros'), ('Licencia no remunerada', 'Licencia no remunerada')], max_length=50, null=True, verbose_name='Turno reprogramación'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='motivo_incumplimiento',
            field=models.CharField(blank=True, choices=[('Calamidad domestica', 'Calamidad domestica'), ('Incapacidad EPS', 'Incapacidad EPS'), ('Permiso remunerado', 'Permiso remunerado'), ('Permiso no remunerado', 'Permiso no remunerado'), ('Cambio de turno', 'Cambio de turno'), ('Día de la familia', 'Día de la familia'), ('Renuncia', 'Renuncia'), ('Daño máquina', 'Daño máquina'), ('Falta de material', 'Falta de material'), ('Incapacidad ARL', 'Incapacidad ARL'), ('No justificado', 'No justificado'), ('Vacaciones', 'Vacaciones')], max_length=100, null=True, verbose_name='Motivo incumplimiento'),
        ),
    ]
