# Generated by Django 3.2.6 on 2021-12-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebasensayo',
            name='elaborado_por_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='id_producto_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='id_pruebas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.pruebas', verbose_name='Prueba y/o ensayo'),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='modificado_por_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='elaborado_por_n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_n', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='id_norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.normas', verbose_name='Norma'),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='id_producto_n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='modificado_por_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_n', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='elaborado_por_ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_ca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='id_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.atributos', verbose_name='Atributo'),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='id_producto_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='modificado_por_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_ca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='elaborado_por_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='id_dimensiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.dimensiones', verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='id_producto_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='modificado_por_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
