# Generated by Django 3.2.6 on 2022-07-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebasensayo',
            name='elaborado_por_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='id_producto_p',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='id_pruebas',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.pruebas', verbose_name='Prueba y/o ensayo'),
        ),
        migrations.AddField(
            model_name='pruebasensayo',
            name='modificado_por_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productos_colores',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.colores', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productos_colores',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ManyToManyField(through='Productos.Productos_colores', to='Productos.Colores'),
        ),
        migrations.AddField(
            model_name='producto',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='elaborado_por_n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_n', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='id_norma',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.normas', verbose_name='Norma'),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='id_producto_n',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='normasaplicable',
            name='modificado_por_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_n', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='elaborado_por_ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_ca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='id_atributo',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.atributos', verbose_name='Atributo'),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='id_producto_a',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='controlatributo',
            name='modificado_por_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_ca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='elaborado_por_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='id_dimensiones',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.dimensiones', verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='id_producto_c',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='caracteristicasdimensionale',
            name='modificado_por_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
