# Generated by Django 3.2.6 on 2021-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebasensayo',
            name='tolerancia_p',
            field=models.FloatField(verbose_name='Tolerancia'),
        ),
    ]
