# Generated by Django 3.2.6 on 2022-07-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
    ]
