# Generated by Django 3.2.6 on 2022-10-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20220730_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='productos_colores',
            name='codigo_producto',
            field=models.CharField(max_length=255, null=True, verbose_name='Código de producto'),
        ),
    ]
