# Generated by Django 3.2.6 on 2022-04-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20220402_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasdimensionale',
            name='id_dimensiones',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.dimensiones', verbose_name='Dimensión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caracteristicasdimensionale',
            name='id_producto_c',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlatributo',
            name='id_atributo',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.atributos', verbose_name='Atributo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlatributo',
            name='id_producto_a',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normasaplicable',
            name='id_norma',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.normas', verbose_name='Norma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normasaplicable',
            name='id_producto_n',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='diagrama',
            field=models.ImageField(blank=True, null=True, upload_to='Produccion/plane', verbose_name='Diagrama'),
        ),
        migrations.AlterField(
            model_name='pruebasensayo',
            name='id_producto_p',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Nombre del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruebasensayo',
            name='id_pruebas',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.pruebas', verbose_name='Prueba y/o ensayo'),
            preserve_default=False,
        ),
    ]
