# Generated by Django 3.2.6 on 2023-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_auto_20230723_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_colores',
            name='version_documento',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión ficha técnica'),
        ),
    ]
