# Generated by Django 3.2.6 on 2023-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_auto_20230807_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_colores',
            name='dosificacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Dosificación'),
        ),
    ]
