# Generated by Django 3.2.6 on 2023-08-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_productos_colores_version_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_colores',
            name='dosificacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Dosificación'),
        ),
    ]
